apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce #Find an instance of storage that supports this access mode
  resources:
    requests:
      storage: 2Gi